name: Build and Release from Merged PR

permissions:
  contents: write 

on:
  pull_request:
    types: [closed]
    branches: [master]
  workflow_dispatch:

jobs:
  create-release:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0
          name: Release v1.0
          generate_release_notes: false
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
